# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-13 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglog',
            old_name='emails',
            new_name='email',
        ),
    ]
