# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-13 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20250213_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='body_test',
            new_name='body_text',
        ),
    ]
