# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-17 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createmailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='sender_email',
        ),
    ]
